// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartProxy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3, arg4, arg5);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function Test1() {
  return window['go']['main']['App']['Test1']();
}
