// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStatus():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function StartProxy(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<main.StartProxyResult>;

export function StopProxy():Promise<main.StopProxyResult>;

export function Test1():Promise<main.Test1Result>;
